if( NOT ARGOS_COMPILE_REAL_SWARMANOID )
  if( APPLE )
    set(CMAKE_CXX_FLAGS_RELEASE "-O2 -Wall -DNDEBUG -ffast-math -undefined dynamic_lookup" CACHE STRING "Flags used by the compiler during release builds" FORCE)
    set(CMAKE_C_FLAGS_RELEASE "-O2 -Wall -DNDEBUG -ffast-math -std=gnu99 -undefined dynamic_lookup" CACHE STRING "Flags used by the compiler during release builds" FORCE)
    set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-Os -Wall -ggdb3 -DNDEBUG -ffast-math -undefined dynamic_lookup" CACHE STRING "Flags used by the compiler during Release with Debug Info builds" FORCE)
    set(CMAKE_C_FLAGS_RELWITHDEBINFO "-Os -Wall -ggdb3 -DNDEBUG -ffast-math -std=gnu99 -undefined dynamic_lookup" CACHE STRING "Flags used by the compiler during Release with Debug Info builds" FORCE)
    set(CMAKE_CXX_FLAGS_DEBUG "-ggdb3 -Wall -undefined dynamic_lookup" CACHE STRING "Flags used by the compiler during debug builds" FORCE)
    set(CMAKE_C_FLAGS_DEBUG "-ggdb3 -Wall -std=gnu99 -undefined dynamic_lookup" CACHE STRING "Flags used by the compiler during debug builds" FORCE)
    set(CMAKE_CXX_FLAGS "-ggdb3 -Wall -undefined dynamic_lookup" CACHE STRING "Flags used by the compiler during all builds" FORCE)
    set(CMAKE_C_FLAGS "-ggdb3 -Wall -std=gnu99 -undefined dynamic_lookup" CACHE STRING "Flags used by the compiler during all builds" FORCE)
  else( APPLE )
    set(CMAKE_CXX_FLAGS_RELEASE "-O2 -Wall -DNDEBUG -ffast-math" CACHE STRING "Flags used by the compiler during release builds" FORCE)
    set(CMAKE_C_FLAGS_RELEASE "-O2 -Wall -DNDEBUG -ffast-math -std=gnu99" CACHE STRING "Flags used by the compiler during release builds" FORCE)
    set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-Os -Wall -ggdb3 -DNDEBUG -ffast-math" CACHE STRING "Flags used by the compiler during Release with Debug Info builds" FORCE)
    set(CMAKE_C_FLAGS_RELWITHDEBINFO "-Os -Wall -ggdb3 -DNDEBUG -ffast-math -std=gnu99" CACHE STRING "Flags used by the compiler during Release with Debug Info builds" FORCE)
    set(CMAKE_CXX_FLAGS_DEBUG "-ggdb3 -Wall" CACHE STRING "Flags used by the compiler during debug builds" FORCE)
    set(CMAKE_C_FLAGS_DEBUG "-ggdb3 -Wall -std=gnu99" CACHE STRING "Flags used by the compiler during debug builds" FORCE)
    set(CMAKE_CXX_FLAGS "-ggdb3 -Wall" CACHE STRING "Flags used by the compiler during all builds" FORCE)
    set(CMAKE_C_FLAGS "-ggdb3 -Wall -std=gnu99" CACHE STRING "Flags used by the compiler during all builds" FORCE)
  endif( APPLE )
endif( NOT ARGOS_COMPILE_REAL_SWARMANOID )
